/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AbTestVersionClicksInner {
    /// URL of the link
    #[serde(rename = "link")]
    pub link: String,
    /// Number of times a link is clicked
    #[serde(rename = "clicksCount")]
    pub clicks_count: f32,
    /// Percentage of clicks of link with respect to total clicks
    #[serde(rename = "clickRate")]
    pub click_rate: String,
}

impl AbTestVersionClicksInner {
    pub fn new(link: String, clicks_count: f32, click_rate: String) -> AbTestVersionClicksInner {
        AbTestVersionClicksInner {
            link,
            clicks_count,
            click_rate,
        }
    }
}


