/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateEmailCampaignRecipients : List ids to include/exclude from campaign



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEmailCampaignRecipients {
    /// List ids to exclude from the campaign
    #[serde(rename = "exclusionListIds", skip_serializing_if = "Option::is_none")]
    pub exclusion_list_ids: Option<Vec<i64>>,
    /// Mandatory if scheduledAt is not empty. List Ids to send the campaign to
    #[serde(rename = "listIds", skip_serializing_if = "Option::is_none")]
    pub list_ids: Option<Vec<i64>>,
}

impl CreateEmailCampaignRecipients {
    /// List ids to include/exclude from campaign
    pub fn new() -> CreateEmailCampaignRecipients {
        CreateEmailCampaignRecipients {
            exclusion_list_ids: None,
            list_ids: None,
        }
    }
}


