/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateContact {
    /// Email address of the user. Mandatory if \"SMS\" field is not passed in \"attributes\" parameter. Mobile Number in \"SMS\" field should be passed with proper country code. For example {\"SMS\":\"+91xxxxxxxxxx\"} or {\"SMS\":\"0091xxxxxxxxxx\"}
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Pass the set of attributes and their values. These attributes must be present in your SendinBlue account. For eg. {\"FNAME\":\"Elly\", \"LNAME\":\"Roger\"}
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    /// Set this field to blacklist the contact for emails (emailBlacklisted = true)
    #[serde(rename = "emailBlacklisted", skip_serializing_if = "Option::is_none")]
    pub email_blacklisted: Option<bool>,
    /// Set this field to blacklist the contact for SMS (smsBlacklisted = true)
    #[serde(rename = "smsBlacklisted", skip_serializing_if = "Option::is_none")]
    pub sms_blacklisted: Option<bool>,
    /// Ids of the lists to add the contact to
    #[serde(rename = "listIds", skip_serializing_if = "Option::is_none")]
    pub list_ids: Option<Vec<i64>>,
    /// Facilitate to update the existing contact in the same request (updateEnabled = true)
    #[serde(rename = "updateEnabled", skip_serializing_if = "Option::is_none")]
    pub update_enabled: Option<bool>,
    /// transactional email forbidden sender for contact. Use only for email Contact ( only available if updateEnabled = true )
    #[serde(rename = "smtpBlacklistSender", skip_serializing_if = "Option::is_none")]
    pub smtp_blacklist_sender: Option<Vec<String>>,
}

impl CreateContact {
    pub fn new() -> CreateContact {
        CreateContact {
            email: None,
            attributes: None,
            email_blacklisted: None,
            sms_blacklisted: None,
            list_ids: None,
            update_enabled: None,
            smtp_blacklist_sender: None,
        }
    }
}


