/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */

/// GetExtendedClientAllOfAddress : Address informations



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetExtendedClientAllOfAddress {
    /// Street information
    #[serde(rename = "street")]
    pub street: String,
    /// City information
    #[serde(rename = "city")]
    pub city: String,
    /// Zip Code information
    #[serde(rename = "zipCode")]
    pub zip_code: String,
    /// Country information
    #[serde(rename = "country")]
    pub country: String,
}

impl GetExtendedClientAllOfAddress {
    /// Address informations
    pub fn new(street: String, city: String, zip_code: String, country: String) -> GetExtendedClientAllOfAddress {
        GetExtendedClientAllOfAddress {
            street,
            city,
            zip_code,
            country,
        }
    }
}


