/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetStatsByDevice {
    /// Statistics of the campaign on the basis of desktop devices
    #[serde(rename = "desktop", skip_serializing_if = "Option::is_none")]
    pub desktop: Option<::std::collections::HashMap<String, crate::models::GetDeviceBrowserStats>>,
    /// Statistics of the campaign on the basis of mobile devices
    #[serde(rename = "mobile", skip_serializing_if = "Option::is_none")]
    pub mobile: Option<::std::collections::HashMap<String, crate::models::GetDeviceBrowserStats>>,
    /// Statistics of the campaign on the basis of tablet devices
    #[serde(rename = "tablet", skip_serializing_if = "Option::is_none")]
    pub tablet: Option<::std::collections::HashMap<String, crate::models::GetDeviceBrowserStats>>,
    /// Statistics of the campaign on the basis of unknown devices
    #[serde(rename = "unknown", skip_serializing_if = "Option::is_none")]
    pub unknown: Option<::std::collections::HashMap<String, crate::models::GetDeviceBrowserStats>>,
}

impl GetStatsByDevice {
    pub fn new() -> GetStatsByDevice {
        GetStatsByDevice {
            desktop: None,
            mobile: None,
            tablet: None,
            unknown: None,
        }
    }
}


