/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */

/// GetChildInfoAllOfStatistics : Statistics about your child account activity



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetChildInfoAllOfStatistics {
    /// Overall emails sent for the previous month
    #[serde(rename = "previousMonthTotalSent", skip_serializing_if = "Option::is_none")]
    pub previous_month_total_sent: Option<i64>,
    /// Overall emails sent for current month
    #[serde(rename = "currentMonthTotalSent", skip_serializing_if = "Option::is_none")]
    pub current_month_total_sent: Option<i64>,
    /// Overall emails sent for since the account exists
    #[serde(rename = "totalSent", skip_serializing_if = "Option::is_none")]
    pub total_sent: Option<i64>,
}

impl GetChildInfoAllOfStatistics {
    /// Statistics about your child account activity
    pub fn new() -> GetChildInfoAllOfStatistics {
        GetChildInfoAllOfStatistics {
            previous_month_total_sent: None,
            current_month_total_sent: None,
            total_sent: None,
        }
    }
}


