/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetContactCampaignStatsTransacAttributesInner {
    /// Date of the order
    #[serde(rename = "orderDate")]
    pub order_date: String,
    /// Price of the order
    #[serde(rename = "orderPrice")]
    pub order_price: f32,
    /// ID of the order
    #[serde(rename = "orderId")]
    pub order_id: i64,
}

impl GetContactCampaignStatsTransacAttributesInner {
    pub fn new(order_date: String, order_price: f32, order_id: i64) -> GetContactCampaignStatsTransacAttributesInner {
        GetContactCampaignStatsTransacAttributesInner {
            order_date,
            order_price,
            order_id,
        }
    }
}


