/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDeviceBrowserStats {
    /// Number of total clicks for the campaign using the particular browser
    #[serde(rename = "clickers")]
    pub clickers: i64,
    /// Number of unique clicks for the campaign using the particular browser
    #[serde(rename = "uniqueClicks")]
    pub unique_clicks: i64,
    /// Number of openings for the campaign using the particular browser
    #[serde(rename = "viewed")]
    pub viewed: i64,
    /// Number of unique openings for the campaign using the particular browser
    #[serde(rename = "uniqueViews")]
    pub unique_views: i64,
}

impl GetDeviceBrowserStats {
    pub fn new(clickers: i64, unique_clicks: i64, viewed: i64, unique_views: i64) -> GetDeviceBrowserStats {
        GetDeviceBrowserStats {
            clickers,
            unique_clicks,
            viewed,
            unique_views,
        }
    }
}


