/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSmsCampaignsCampaignsInnerAllOfStatistics {
    /// Number of delivered SMS
    #[serde(rename = "delivered")]
    pub delivered: i64,
    /// Number of sent SMS
    #[serde(rename = "sent")]
    pub sent: i64,
    /// Number of processing SMS
    #[serde(rename = "processing")]
    pub processing: i64,
    /// Number of softbounced SMS
    #[serde(rename = "softBounces")]
    pub soft_bounces: i64,
    /// Number of hardbounced SMS
    #[serde(rename = "hardBounces")]
    pub hard_bounces: i64,
    /// Number of unsubscription SMS
    #[serde(rename = "unsubscriptions")]
    pub unsubscriptions: i64,
    /// Number of replies to the SMS
    #[serde(rename = "answered")]
    pub answered: i64,
}

impl GetSmsCampaignsCampaignsInnerAllOfStatistics {
    pub fn new(delivered: i64, sent: i64, processing: i64, soft_bounces: i64, hard_bounces: i64, unsubscriptions: i64, answered: i64) -> GetSmsCampaignsCampaignsInnerAllOfStatistics {
        GetSmsCampaignsCampaignsInnerAllOfStatistics {
            delivered,
            sent,
            processing,
            soft_bounces,
            hard_bounces,
            unsubscriptions,
            answered,
        }
    }
}


