/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */

/// RequestContactImportNewList : To create a new list and import the contacts into it, pass the listName and an optional folderId.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestContactImportNewList {
    /// List with listName will be created first and users will be imported in it (Mandatory if listIds is empty).
    #[serde(rename = "listName", skip_serializing_if = "Option::is_none")]
    pub list_name: Option<String>,
    /// Id of the folder where this new list shall be created (Mandatory if listName is not empty).
    #[serde(rename = "folderId", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<i64>,
}

impl RequestContactImportNewList {
    /// To create a new list and import the contacts into it, pass the listName and an optional folderId.
    pub fn new() -> RequestContactImportNewList {
        RequestContactImportNewList {
            list_name: None,
            folder_id: None,
        }
    }
}


