/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateChildAccountStatus {
    /// Status of Transactional Email Platform activation for your account (true=enabled, false=disabled)
    #[serde(rename = "transactionalEmail", skip_serializing_if = "Option::is_none")]
    pub transactional_email: Option<bool>,
    /// Status of Transactional SMS Platform activation for your account (true=enabled, false=disabled)
    #[serde(rename = "transactionalSms", skip_serializing_if = "Option::is_none")]
    pub transactional_sms: Option<bool>,
    /// Status of Marketing Automation Platform activation for your account (true=enabled, false=disabled)
    #[serde(rename = "marketingAutomation", skip_serializing_if = "Option::is_none")]
    pub marketing_automation: Option<bool>,
    /// Status of SMS Campaign Platform activation for your account (true=enabled, false=disabled)
    #[serde(rename = "smsCampaign", skip_serializing_if = "Option::is_none")]
    pub sms_campaign: Option<bool>,
}

impl UpdateChildAccountStatus {
    pub fn new() -> UpdateChildAccountStatus {
        UpdateChildAccountStatus {
            transactional_email: None,
            transactional_sms: None,
            marketing_automation: None,
            sms_campaign: None,
        }
    }
}


