/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateCampaignStatus : Status of the campaign



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateCampaignStatus {
    /// Note:- replicateTemplate status will be available only for template type campaigns.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl UpdateCampaignStatus {
    /// Status of the campaign
    pub fn new() -> UpdateCampaignStatus {
        UpdateCampaignStatus {
            status: None,
        }
    }
}

/// Note:- replicateTemplate status will be available only for template type campaigns.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "archive")]
    Archive,
    #[serde(rename = "darchive")]
    Darchive,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "replicate")]
    Replicate,
    #[serde(rename = "replicateTemplate")]
    ReplicateTemplate,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for Status {
    fn default() -> Status {
        Self::Suspended
    }
}

